//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        public int Id { get; set; }
        public System.DateTime CompletedDate { get; set; }
        public string KeyOutcomes { get; set; }
        public string MajorRoadblocks { get; set; }
        public string KeyLearning { get; set; }
        public string ThingsCouldHaveBeenBetter { get; set; }
        public string RemrksFromTeamLead { get; set; }
        public string RemarksFromDepartmentLead { get; set; }
        public string RemarksFromManager { get; set; }
        public int ProjectId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
