//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMilestone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectMilestone()
        {
            this.TaskDependencies = new HashSet<TaskDependency>();
            this.TaskDependencies1 = new HashSet<TaskDependency>();
        }
    
        public int Id { get; set; }
        public string TaskDetail { get; set; }
        public int NumberOfDay { get; set; }
        public string ImpactedFunctionalities { get; set; }
        public string Objective { get; set; }
        public string TaskDeliverables { get; set; }
        public string Assumption { get; set; }
        public string Constraints { get; set; }
        public Nullable<System.DateTime> EstimatedStartDate { get; set; }
        public Nullable<System.DateTime> EstimatedCompletionDate { get; set; }
        public System.DateTime ActualStartDate { get; set; }
        public System.DateTime ActualCompletionDate { get; set; }
        public double PercentageCompletion { get; set; }
        public string Status { get; set; }
        public int EmployeeId { get; set; }
        public int ProjectId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDependency> TaskDependencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDependency> TaskDependencies1 { get; set; }
    }
}
