//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Clients = new HashSet<Client>();
            this.Contractors = new HashSet<Contractor>();
            this.ProjectDetails = new HashSet<ProjectDetail>();
            this.ProjectMilestones = new HashSet<ProjectMilestone>();
            this.ProjectTeams = new HashSet<ProjectTeam>();
            this.ProjectTeamResponsibilites = new HashSet<ProjectTeamResponsibilite>();
            this.ProjectTeamRoles = new HashSet<ProjectTeamRole>();
            this.RiskRegisters = new HashSet<RiskRegister>();
            this.TeamLeads = new HashSet<TeamLead>();
            this.TechnologyPlatforms = new HashSet<TechnologyPlatform>();
        }
    
        public int Id { get; set; }
        public int ProjectTypeId { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public string Title { get; set; }
        public int ProjectCategoryId { get; set; }
        public System.DateTime StartDate { get; set; }
        public string EndDate { get; set; }
        public string Introduction { get; set; }
        public string KeyDetails { get; set; }
        public string Scope { get; set; }
        public int ProjectStatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contractor> Contractors { get; set; }
        public virtual ProjectCategory ProjectCategory { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectMilestone> ProjectMilestones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTeam> ProjectTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTeamResponsibilite> ProjectTeamResponsibilites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTeamRole> ProjectTeamRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskRegister> RiskRegisters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamLead> TeamLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnologyPlatform> TechnologyPlatforms { get; set; }
    }
}
