//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskArea
    {
        public int Id { get; set; }
        public string RiskAreas { get; set; }
        public int RiskRegisterId { get; set; }
    
        public virtual RiskRegister RiskRegister { get; set; }
    }
}
