//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskRegister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskRegister()
        {
            this.RiskAreas = new HashSet<RiskArea>();
        }
    
        public int Id { get; set; }
        public bool CurrentStatus { get; set; }
        public string RiskImpact { get; set; }
        public string ProbabilityOfOccurrence { get; set; }
        public string RiskDescription { get; set; }
        public string ProjectImpact { get; set; }
        public string Symptoms { get; set; }
        public string RiskResponseStrategy { get; set; }
        public string ResponseStrategy { get; set; }
        public string ContingencyPlan { get; set; }
        public int ProjectId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public bool Status { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskArea> RiskAreas { get; set; }
    }
}
